version: '3.8'
name: "Cognitive-Wizard"

services:
  ai-backend:
    build:
      context: ./server/py_server
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]
    restart: unless-stopped

  api-gateway:
    build:
      context: ./server/js_server
    ports:
      - "3000:3000"
    depends_on:
      - ai-backend
    environment:
      # Internal Docker DNS automatically resolves service names
      - PY_SERVER_URL=http://ai-backend:8000
    restart: unless-stopped

  frontend:
    build:
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - api-gateway
    restart: unless-stopped
