name: Cognitive-Wizard

services:

  ai-backend:
    build:
      context: ./server/py_server
    ports:
      - "8000:8000"
    env_file:
      - ./server/py_server/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped

  api-gateway:
    build:
      context: ./server/js_server
    ports:
      - "3000:3000"
    depends_on:
      - ai-backend
    env_file:
      - ./server/js_server/.env
    environment:
      PY_SERVER_URL: http://ai-backend:8000
    restart: unless-stopped

  frontend:
    build:
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - api-gateway
    restart: unless-stopped
