"""
tests/test_regression_baseline.py
=================================
Regression protection baseline test suite.
Validates existing capabilities:
- RAG document formatting and chain setup
- Summarization preprocessing and chunking
- Roadmap PDF generation
- Course generation schemas and quality gate validation
"""

import pytest
from services.rag.chains.v1_rag_chain import _format_docs
from services.summarization.preprocess.chunker import TextChunker
from services.summarization.preprocess.text_cleaner import TextCleaner
from services.roadmap_pdf_service import generate_roadmap_pdf
from schemas.course_generation import (
    CourseBlueprintSchema,
    CourseLessonSchema,
    LessonSectionSchema,
    LessonExerciseSchema,
    QualityGateResultSchema,
)
from agents.nodes.quality_gate_node import _validate_lesson, _assemble_course_package


def test_rag_doc_formatting():
    """Verify RAG document formatting helper handles diverse document structures."""
    docs = [
        {"page_content": "Chunk 1 content"},
        {"text": "Chunk 2 content"},
    ]
    formatted = _format_docs(docs)
    assert "Chunk 1 content" in formatted
    assert "Chunk 2 content" in formatted


def test_summarization_preprocessing():
    """Verify Summarization cleaner and chunker work as expected."""
    raw_text = "   This is a test paragraph with extra spaces.   \n\nAnother paragraph here.  "
    cleaned = TextCleaner.clean(raw_text)
    assert "extra spaces." in cleaned

    chunks = TextChunker.chunk(cleaned * 10, max_chunk_size=200, overlap=20)
    assert len(chunks) >= 1
    assert all(len(c) > 0 for c in chunks)


def test_roadmap_pdf_generation():
    """Verify Roadmap PDF service generates valid PDF bytes."""
    sample_content = {
        "title": "Machine Learning Engineer Roadmap",
        "description": "A comprehensive guide to mastering ML",
        "prerequisites": ["Python Basics", "Linear Algebra"],
        "outcomes": ["Build neural networks", "Deploy ML models"],
        "learning_phases": ["Phase 1: Foundations", "Phase 2: Deep Learning"],
        "phasewise_modules": [
            {
                "phase": "Phase 1: Foundations",
                "modules": [
                    {
                        "title": "Python for Data Science",
                        "description": "Core libraries: NumPy, Pandas, Scikit-learn",
                        "estimated_time": "3 weeks",
                        "difficulty": "beginner",
                        "topics": [
                            {
                                "name": "NumPy Arrays",
                                "details": "Broadcasting, indexing, and vectorization",
                                "importance": "High",
                            }
                        ],
                    }
                ],
            }
        ],
        "references": {
            "official_docs": [
                {
                    "title": "Python Documentation",
                    "url": "https://docs.python.org/3/",
                    "source": "Python.org",
                }
            ]
        },
    }
    pdf_bytes = generate_roadmap_pdf(sample_content, topic_name="Machine Learning")
    assert isinstance(pdf_bytes, bytes)
    assert pdf_bytes.startswith(b"%PDF")
    assert len(pdf_bytes) > 500


def test_course_schema_and_quality_gate_baseline():
    """Verify CourseBlueprintSchema and CourseLessonSchema validate correctly."""
    blueprint_data = {
        "title": "Introduction to AI",
        "description": "Comprehensive course curriculum blueprint generated by learning architect",
        "domain": "computer_science",
        "domain_label": "Computer Science",
        "exercise_paradigm": "coding",
        "chapters": [
            {
                "title": "Chapter 1: Foundations",
                "description": "Fundamental concepts in modern artificial intelligence",
                "estimated_duration": "2 weeks",
                "modules": [
                    {
                        "title": "Module 1: Search Algorithms",
                        "description": "Uninformed and heuristic search methodologies",
                        "difficulty": "beginner",
                        "estimated_time": "3 hours",
                        "lessons": [
                            {
                                "title": "Breadth-First Search",
                                "learning_objectives": ["Implement BFS in Python"],
                                "estimated_time": "20 minutes",
                            }
                        ],
                    }
                ],
            }
        ],
    }
    blueprint = CourseBlueprintSchema.model_validate(blueprint_data)
    assert len(blueprint.chapters) == 1

    lesson_data = {
        "title": "Breadth-First Search",
        "overview": "Detailed overview of BFS traversing trees level by level in systematic fashion.",
        "estimated_time": "20 minutes",
        "sections": [
            {
                "section_type": "explanation",
                "title": "Core Mechanism",
                "body": "Breadth-First Search systematically visits vertices level by level using a FIFO queue data structure to guarantee shortest paths in unweighted graphs.",
            },
            {
                "section_type": "example",
                "title": "Graph Traversal Example",
                "body": "Consider a graph with vertices A, B, C. Starting from A, BFS explores all neighbors B and C before exploring neighbors of B.",
            },
        ],
        "exercises": [
            {
                "title": "Implement BFS",
                "description": "Write a Python function using collections.deque to perform BFS traversal.",
                "exercise_type": "coding",
                "starter_code": "from collections import deque\ndef bfs(graph, start):\n    pass",
                "language": "python",
            }
        ],
    }
    lesson = CourseLessonSchema.model_validate(lesson_data)
    assert lesson.title == "Breadth-First Search"

    wrapper = {"lesson": lesson_data, "generation_status": "generated"}
    is_valid, issues = _validate_lesson(wrapper, {})
    assert is_valid
    assert len(issues) == 0
