/**
 * CourseLesson.js
 * ===============
 * The atomic content unit inside a module. Each lesson is a self-contained
 * learning experience (explanation + examples + resources + exercises).
 *
 * Hierarchy: CourseModule → CourseLesson → LessonSection / LessonResource / LessonExercise
 */

const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/db');
const WizardContent = require('./WizardContent');
const CourseModule = require('./CourseModule');

const CourseLesson = sequelize.define('CourseLesson', {
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },

  /** FK to parent module */
  module_id: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: { model: CourseModule, key: 'id' },
    onDelete: 'CASCADE',
  },

  /** FK to root WizardContent for direct queries */
  content_id: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: { model: WizardContent, key: 'id' },
    onDelete: 'CASCADE',
  },

  /** Lesson title, e.g. "Definition, History and Evolution of AI" */
  title: {
    type: DataTypes.STRING(500),
    allowNull: false,
  },

  /**
   * Short 2-4 sentence overview / learning summary shown in the lesson card.
   * Rendered before the full content sections.
   */
  overview: {
    type: DataTypes.TEXT,
    allowNull: true,
  },

  /** Estimated time to complete this lesson, e.g. "20 minutes" */
  estimated_time: {
    type: DataTypes.STRING(100),
    allowNull: true,
  },

  /** Display order within the module */
  sequence: {
    type: DataTypes.INTEGER,
    allowNull: false,
    defaultValue: 1,
  },

  /**
   * Generation + review lifecycle:
   *  draft      → generated by lesson_generator_node
   *  reviewed   → passed pedagogical_reviewer_node
   *  published  → part of a published course
   */
  status: {
    type: DataTypes.ENUM('draft', 'reviewed', 'published'),
    allowNull: false,
    defaultValue: 'draft',
  },
}, {
  tableName: 'course_lessons',
  timestamps: true,
  createdAt: 'created_at',
  updatedAt: 'updated_at',
});

// Associations
CourseModule.hasMany(CourseLesson, { foreignKey: 'module_id', as: 'lessons' });
CourseLesson.belongsTo(CourseModule, { foreignKey: 'module_id', as: 'module' });

WizardContent.hasMany(CourseLesson, { foreignKey: 'content_id', as: 'course_lessons' });
CourseLesson.belongsTo(WizardContent, { foreignKey: 'content_id', as: 'course' });

module.exports = CourseLesson;
