"""user table changed

Revision ID: 0a297f05a75f
Revises: 7d504f8e6787
Create Date: 2026-05-28 14:44:23.862070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0a297f05a75f'
down_revision: Union[str, Sequence[str], None] = '7d504f8e6787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_query_logs_id'), table_name='rag_query_logs')
    op.drop_index(op.f('ix_rag_query_logs_session_id'), table_name='rag_query_logs')
    op.drop_index(op.f('ix_rag_query_logs_user_id'), table_name='rag_query_logs')
    op.drop_table('rag_query_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_query_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('question', mysql.TEXT(), nullable=False),
    sa.Column('answer', mysql.TEXT(), nullable=False),
    sa.Column('contexts', mysql.JSON(), nullable=True),
    sa.Column('context_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latency_retrieval_ms', mysql.FLOAT(), nullable=True),
    sa.Column('latency_generation_ms', mysql.FLOAT(), nullable=True),
    sa.Column('latency_total_ms', mysql.FLOAT(), nullable=True),
    sa.Column('sources', mysql.JSON(), nullable=True),
    sa.Column('metrics', mysql.JSON(), nullable=True),
    sa.Column('log_metadata', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_rag_query_logs_user_id'), 'rag_query_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_rag_query_logs_session_id'), 'rag_query_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_rag_query_logs_id'), 'rag_query_logs', ['id'], unique=False)
    # ### end Alembic commands ###
