"""Add wizard_contents table

Revision ID: ec28c63ef14d
Revises: 0a297f05a75f
Create Date: 2026-06-18 17:14:38.795436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec28c63ef14d'
down_revision: Union[str, Sequence[str], None] = '0a297f05a75f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wizard_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wizard_contents_id'), 'wizard_contents', ['id'], unique=False)
    op.create_index(op.f('ix_wizard_contents_user_id'), 'wizard_contents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wizard_contents_user_id'), table_name='wizard_contents')
    op.drop_index(op.f('ix_wizard_contents_id'), table_name='wizard_contents')
    op.drop_table('wizard_contents')
    # ### end Alembic commands ###
