"""
schemas/course_generation.py
============================
Pydantic v2 schemas for the entire course generation pipeline.

Each schema maps 1-to-1 with a DB model, enabling:
    - Structured LLM output (via .with_structured_output())
    - Agent state validation at each node boundary
    - Webhook payload serialization to the JS server

Pipeline order:
    CourseBlueprintSchema   → Learning Architect Node output
    EvidencePackageSchema   → Research Agent Node output
    CourseLessonSchema      → Lesson Generator Node output (per lesson)
    ReviewedLessonSchema    → Pedagogical Reviewer Node output (per lesson)
    CoursePackageSchema     → Quality Gate Node final output (written to DB)
"""

from __future__ import annotations
from typing import Literal, Optional, List, Any
from pydantic import BaseModel, Field, field_validator, model_validator

# ─────────────────────────────────────────────────────────────────────────────
# Blueprint models (Learning Architect → structure-only, no prose)
# ─────────────────────────────────────────────────────────────────────────────


class LessonBlueprintSchema(BaseModel):
    """Lightweight lesson descriptor — generated by the architect, NOT a full lesson."""

    title: str = Field(..., min_length=3, description="Lesson title")
    learning_objectives: List[str] = Field(
        default_factory=list,
        description="2-4 specific things the learner will know/do after this lesson",
    )
    estimated_time: str = Field(default="20 minutes", description="e.g. '20 minutes'")


class ModuleBlueprintSchema(BaseModel):
    """Module descriptor with lesson blueprints — no full content yet."""

    title: str = Field(..., min_length=3)
    description: str = Field(..., min_length=10)
    difficulty: Literal["beginner", "intermediate", "advanced"] = "beginner"
    estimated_time: str = Field(default="2 hours")
    learning_objectives: List[str] = Field(default_factory=list)
    key_takeaways: List[str] = Field(default_factory=list)
    lessons: List[LessonBlueprintSchema] = Field(
        ...,
        min_length=1,
        description="Lesson blueprints for this module — architect generates titles+objectives only",
    )

    @field_validator("difficulty", mode="before")
    @classmethod
    def normalize_difficulty(cls, v: Any) -> str:
        if isinstance(v, str):
            val = v.lower().strip()
            mapping = {
                "easy": "beginner",
                "medium": "intermediate",
                "hard": "advanced",
            }
            if val in mapping:
                return mapping[val]
            if val in ("beginner", "intermediate", "advanced"):
                return val
        return "beginner"


class ChapterBlueprintSchema(BaseModel):
    """Chapter descriptor — groups related modules in course outline."""

    title: str = Field(..., min_length=3)
    description: str = Field(..., min_length=10)
    estimated_duration: str = Field(default="2 weeks")
    modules: List[ModuleBlueprintSchema] = Field(..., min_length=1)


class CourseBlueprintSchema(BaseModel):
    """
    Full course structure blueprint — produced by Learning Architect Node.
    Contains NO lesson prose, only structure and objectives.
    Hierarchy: Course -> Chapters -> Modules -> Lessons
    """

    title: str = Field(..., min_length=3)
    description: str = Field(..., min_length=20)
    target_audience: str = Field(default="General Learners")
    domain: str = Field(
        default="general",
        description="Academic/professional domain: computer_science, engineering, natural_sciences, business_finance, humanities, medicine, general",
    )
    domain_label: str = Field(
        default="General",
        description="Human-readable domain name, e.g. 'Geology & Earth Sciences'",
    )
    exercise_paradigm: str = Field(
        default="mixed",
        description="Primary exercise style: coding | calculation | case_study | analysis | reflection",
    )
    course_outcomes: List[str] = Field(default_factory=list)
    prerequisites: List[str] = Field(default_factory=list)
    chapters: List[ChapterBlueprintSchema] = Field(default_factory=list)

    @model_validator(mode="before")
    @classmethod
    def normalize_input_data(cls, data: Any) -> Any:
        if isinstance(data, list):
            # Case 1: list of chapters (items have "modules")
            if len(data) > 0 and all(isinstance(x, dict) and "modules" in x for x in data):
                return {
                    "title": "Comprehensive Course",
                    "description": "Comprehensive course curriculum blueprint generated by learning architect",
                    "domain": "general",
                    "domain_label": "General",
                    "exercise_paradigm": "mixed",
                    "chapters": data,
                }
            # Case 2: single-element list wrapping the course dict
            if len(data) == 1 and isinstance(data[0], dict):
                return data[0]
        return data

    @field_validator("chapters")
    @classmethod
    def validate_chapter_count(cls, v: List) -> List:
        if len(v) > 8:
            raise ValueError("Course should have at most 8 chapters to remain focused")
        return v


# ─────────────────────────────────────────────────────────────────────────────
# Research / Evidence models
# ─────────────────────────────────────────────────────────────────────────────


class EvidenceItemSchema(BaseModel):
    """A single curated resource for a lesson (from Research Agent)."""

    title: str
    url: str
    resource_type: Literal[
        "official_docs",
        "youtube",
        "article",
        "research_paper",
        "course",
        "practice",
        "tool",
        "other",
    ] = "other"
    source: str = ""
    description: Optional[str] = None
    relevance_score: float = Field(default=0.0, ge=0.0, le=1.0)
    supports: List[str] = Field(
        default_factory=list,
        description="Concepts within the lesson this resource supports",
    )


class LessonEvidenceSchema(BaseModel):
    """Evidence package for a single lesson, produced by Research Agent."""

    lesson_title: str
    resources: List[EvidenceItemSchema] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)


# ─────────────────────────────────────────────────────────────────────────────
# Full lesson content models (Lesson Generator Node output)
# ─────────────────────────────────────────────────────────────────────────────


class LessonSectionSchema(BaseModel):
    """
    A typed content block within a lesson.
    Maps to the lesson_sections DB table.
    """

    section_type: Literal[
        "explanation",
        "example",
        "analogy",
        "code",
        "practice",
        "visual_description",
        "common_mistakes",
        "summary",
    ]
    title: Optional[str] = Field(default=None, description="Optional sub-heading")
    body: str = Field(
        ...,
        min_length=50,
        description="Full content body — prose, code, or description",
    )
    language: Optional[str] = Field(
        default=None,
        description="Programming language for code sections (e.g. 'python', 'javascript')",
    )
    sequence: int = Field(default=1, ge=1)

    @field_validator("body")
    @classmethod
    def body_not_empty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Section body cannot be empty")
        return v


class LessonExerciseSchema(BaseModel):
    """
    A practice exercise attached to a lesson.
    Maps to the lesson_exercises DB table.
    Supports multi-domain exercises: coding, calculation, case_study, analysis, reflection.
    """

    title: str = Field(..., min_length=3)
    description: str = Field(..., min_length=15, description="Full problem statement / scenario")
    exercise_type: Literal[
        "coding",
        "calculation",
        "case_study",
        "analysis",
        "reflection",
        "quiz_seed",
    ] = "reflection"
    difficulty: Literal["easy", "medium", "hard"] = "medium"

    @field_validator("exercise_type", mode="before")
    @classmethod
    def normalize_exercise_type(cls, v: Any) -> str:
        if not isinstance(v, str):
            return "reflection"
        v_clean = v.strip().lower()
        mapping = {
            "coding": "coding",
            "code": "coding",
            "programming": "coding",
            "calculation": "calculation",
            "math": "calculation",
            "numerical": "calculation",
            "case_study": "case_study",
            "case": "case_study",
            "scenario": "case_study",
            "analysis": "analysis",
            "critical_thinking": "analysis",
            "reflection": "reflection",
            "qna": "reflection",
            "q&a": "reflection",
            "concept_check": "reflection",
            "conceptual": "reflection",
            "question": "reflection",
            "theory": "reflection",
            "discussion": "reflection",
            "essay": "reflection",
            "short_answer": "reflection",
            "free_response": "reflection",
            "quiz_seed": "quiz_seed",
            "quiz": "quiz_seed",
            "multiple_choice": "quiz_seed",
        }
        return mapping.get(v_clean, "reflection")

    @field_validator("difficulty", mode="before")
    @classmethod
    def normalize_difficulty(cls, v: Any) -> str:
        if not isinstance(v, str):
            return "medium"
        v_clean = v.strip().lower()
        mapping = {
            "beginner": "easy",
            "introductory": "easy",
            "basic": "easy",
            "easy": "easy",
            "intermediate": "medium",
            "medium": "medium",
            "moderate": "medium",
            "advanced": "hard",
            "hard": "hard",
            "expert": "hard",
        }
        return mapping.get(v_clean, "medium")
    starter_code: Optional[str] = Field(
        default=None,
        description="Boilerplate code for coding exercises — NULL for non-coding exercises",
    )
    language: Optional[str] = Field(
        default=None,
        description="Language for coding exercises (e.g. 'python') — NULL for non-coding exercises",
    )
    solution_hint: Optional[str] = Field(
        default=None, description="Hint to unblock learner without giving away solution"
    )
    expected_output: Optional[str] = Field(
        default=None, description="Model answer / expected output / key conclusion"
    )
    sequence: int = Field(default=1, ge=1)


class CourseLessonSchema(BaseModel):
    """
    Full generated lesson with all content.
    Produced by Lesson Generator Node, reviewed by Pedagogical Reviewer Node.
    Maps to course_lessons + lesson_sections + lesson_exercises DB tables.
    """

    title: str = Field(..., min_length=3)
    overview: str = Field(
        ...,
        min_length=50,
        description="2-4 sentence summary shown on the lesson card before opening",
    )
    estimated_time: str = Field(default="20 minutes")
    sections: List[LessonSectionSchema] = Field(
        ...,
        min_length=2,
        description="Ordered content blocks — must include at least explanation + example",
    )
    exercises: List[LessonExerciseSchema] = Field(
        default_factory=list,
        description="Practice exercises (at least 1 coding or reflection exercise recommended)",
    )
    # Resources are attached after Research Agent runs — NOT part of LLM output
    resources: List[EvidenceItemSchema] = Field(default_factory=list)

    @field_validator("sections")
    @classmethod
    def validate_section_types(
        cls, v: List[LessonSectionSchema]
    ) -> List[LessonSectionSchema]:
        types = {s.section_type for s in v}
        if "explanation" not in types:
            raise ValueError(
                "Every lesson must have at least one 'explanation' section"
            )
        return v


# ─────────────────────────────────────────────────────────────────────────────
# Pipeline state wrapper
# ─────────────────────────────────────────────────────────────────────────────


class LessonGenerationResultSchema(BaseModel):
    """
    Wraps the generated lesson with independent state tracking.
    This prevents encoding pipeline status inside the lesson content itself.
    """
    lesson: Optional[CourseLessonSchema] = None
    generation_status: Literal["generated", "failed", "pending"] = "pending"
    review_status: Literal["passed", "failed", "unavailable", "pending"] = "pending"
    error: Optional[str] = None


# ─────────────────────────────────────────────────────────────────────────────
# Pedagogical Review model
# ─────────────────────────────────────────────────────────────────────────────


class LessonReviewSchema(BaseModel):
    """
    Output of Pedagogical Reviewer Node for a single lesson.
    Used to decide PASS (lesson is ready) or FAIL (needs regeneration).
    """

    lesson_title: str
    review_status: Literal["passed", "failed", "unavailable"]
    issues: List[str] = Field(
        default_factory=list,
        description="List of specific issues found — empty if passed",
    )
    suggestions: List[str] = Field(
        default_factory=list,
        description="Improvement suggestions for Lesson Generator on retry",
    )
    # Bloom's taxonomy coverage check
    bloom_levels_covered: List[str] = Field(
        default_factory=list,
        description="Which Bloom's taxonomy levels are addressed: remember/understand/apply/analyze",
    )


# ─────────────────────────────────────────────────────────────────────────────
# Quality Gate model
# ─────────────────────────────────────────────────────────────────────────────


class QualityGateResultSchema(BaseModel):
    """
    Result of the Quality Gate Node.
    Aggregates pass/fail signals across all lessons before publishing.
    """

    passed: bool
    total_lessons: int
    lessons_passed: int
    lessons_failed: int
    critical_issues: List[str] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)


# ─────────────────────────────────────────────────────────────────────────────
# Final course package (written to DB by webhook handler)
# ─────────────────────────────────────────────────────────────────────────────


class CourseModuleFullSchema(BaseModel):
    """Full module with generated lessons — used in the webhook payload."""

    title: str
    description: str
    difficulty: str = "beginner"
    estimated_time: str = "2 hours"
    learning_objectives: List[str] = Field(default_factory=list)
    key_takeaways: List[str] = Field(default_factory=list)
    lessons: List[CourseLessonSchema] = Field(default_factory=list)


class CourseChapterFullSchema(BaseModel):
    """Full chapter with modules and lessons — used in the webhook payload."""

    title: str
    description: str
    estimated_duration: str = "2 weeks"
    modules: List[CourseModuleFullSchema] = Field(default_factory=list)


class CoursePackageSchema(BaseModel):
    """
    Final course package sent from py_server to js_server via webhook.
    This is what gets written to the DB relational tables.
    """

    # Discriminator so webhookAgenticComplete knows which handler to use
    content_type: Literal["course"] = "course"

    title: str
    description: str
    target_audience: str = "General Learners"
    domain: Optional[str] = "general"
    domain_label: Optional[str] = "General"
    exercise_paradigm: Optional[str] = "mixed"
    course_outcomes: List[str] = Field(default_factory=list)
    prerequisites: List[str] = Field(default_factory=list)
    chapters: List[CourseChapterFullSchema] = Field(default_factory=list)
    quality_gate: Optional[QualityGateResultSchema] = None
    warnings: List[str] = Field(default_factory=list)
